package com.example.notification.enums;

public enum ResponsibleService {
    HARDWARE_SERVICE, ADMINISTRATION_SERVICE, PRINTING_SERVICE, DEVOPS_SERVICE, DEVELOPMENT_SERVICE, FACILITIES_SERVICE, PROCUREMENT_SERVICE, WAREHOUSE_SERVICE
}
